// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/structure-planner/CardDetail.tsx": () => import("../components/mockups/structure-planner/CardDetail.tsx"),
  "./components/mockups/structure-planner/CardGrid.tsx": () => import("../components/mockups/structure-planner/CardGrid.tsx"),
  "./components/mockups/structure-planner/DashboardEntry.tsx": () => import("../components/mockups/structure-planner/DashboardEntry.tsx")
};
